[package]
name = "lunatic-vm"
version = "0.1.0"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-wormhole = { path = "../async_wormhole" }
wasmtime = {path = "../wasmtime/crates/wasmtime"}
wasmtime-runtime = {path = "../wasmtime/crates/runtime"}
walrus = "0.18"
smol = "1.2"
easy-parallel = "3"
num_cpus = "1"
crossbeam = "0.8"
anyhow = "1.0"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"
wat = "1.0"
wasmprinter = "0.2"

[[bench]]
name = "lunatic_benchmark"
harness = false

[[test]]
name = "patching"
harness = false